apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: arc-backups
provisioner: file.csi.azure.com
parameters:
  skuName: Standard_LRS          # Lower cost, optimized for backup files
  protocol: smb                  # SMB protocol (can also use NFS)
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
