apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: arc-data
provisioner: disk.csi.azure.com
parameters:
  skuName: Premium_LRS          # High performance SSD
  cachingMode: None             # Caching can be None or ReadOnly, depends on workload
reclaimPolicy: Retain
volumeBindingMode: WaitForFirstConsumer
